apiVersion: apps/v1
kind: Deployment
metadata:
  name: memr
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memr
  template:
    metadata:
      labels:
        app: memr
    spec:
      containers:
      - name: memr
        image: fmurugi/memr:v2
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: memr-config
            
